# QoS override for replaying CX16 + gps bags.
# Usage example:
# ros2 bag play <bag> --qos-profile-overrides-path config/rosbag_play_cx16_reliable_qos.yaml
/cx/cloud:
  history: keep_all
  reliability: reliable
  durability: volatile

/imu_data:
  history: keep_all
  reliability: reliable
  durability: volatile

/fdilink/gnss_fix:
  history: keep_all
  reliability: reliable
  durability: volatile

/ins/velocity:
  history: keep_all
  reliability: reliable
  durability: volatile
